### ISSUE TITLE
Certified PX4 compatible ?

### ISSUE THREAD

**Issue by AlexisTM** [drotek/SMARTNAV-RTK#16]
Hey, 

What does mean "certified PX4 compatible"? Certified by who? What frames are going out of the module? 

I am asking this because U-Blox M8T based solutions usually output NMEA which is not compaitble with the PX4 firmware (but compatible with Ardupilot).

**Comment by klopezal** [comment]
Hello, 

The M8T module is configured at startup to send RAWX and SFRBX messages (which contain the raw data information). Then RTKlib has been modified to create NAV-DOP, NAV-POSLLH, NAV-STATUS and NAV-VELNED ubx binary messages. This is an issue right now because PX4 (and Ardupilot) have moved (or are moving) to NAV-PVT message (which contains all the information summarised in one message). So right now and before porting to this new message it is not compatible with PX4, thanks por pointing out.

**Comment by kikislater** [comment]
And so .... you do not provide patch or update to support NAV-PVT ?

**Comment by AlexisTM** [comment]
Yet, the Ublox Tiny/XL/XXL RTK are compatible with the PX4 firmware right? (based on the ublox M8P)

**Comment by klopezal** [comment]
Yes we will!

**Comment by klopezal** [comment]
And yes Tiny/XL/XXL RTK are directly compatible.

**Comment by AlexisTM** [comment]
Thank you for your fast support Kévin and precise answer.

**Comment by AlexisTM** [comment]
Outdated.
